---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario
spec:
  selector:
    matchLabels:
      app: supermario
  replicas: 4 
  template:
    metadata:
      labels:
        app: supermario
    spec:
      containers:
      - name: supermario
        image: bharathshetty4/supermario
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: supermario-loadbalancer-service
  labels:
    LB: supermario
spec:
  selector:
    app: supermario
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
